spring:
  application:
    name: online-voting-system

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always

  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: masolakabelo@gmail.com
    password: haqucndwzwxttjzq
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 8083


