spring:
  application:
    name: userservice

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always

  h2:
    console:
      enabled: true
server:
  port: 8081


